name: Fetch Data and Send to Telegram

on:
  schedule:
    - cron: '0 0 * * *'  # Run the workflow daily at midnight

jobs:
  fetch_and_send_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script and send data to Telegram
        run: |
          python index.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}

      - name: Create or update sent_messages.json file
        run: |
          echo "[]" > sent_messages.json
        if: success()

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ssc.json || git commit -m "Create ssc.json"
          git commit -m "Update ssc.json" || echo "No changes to commit"
          git pull origin main || echo "No remote changes to pull"
          git push origin main
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
